#!/usr/bin/python3
from os import system, getuid
from time import sleep              #Not Really Useful, Just to fake something important going on ;D 


if getuid() > 0:
    print('[+] I\'ms Going To Ask For Your Permission To Install Myself :D')
    sleep(1)

    print('[+] Ready?')
    sleep(2)


system('sudo mkdir /etc/Umacchanger')

print('[+] Installing...')
system('sudo cp UmacchangerMacAddresses.txt /etc/Umacchanger')

system('sudo cp Umacchanger /bin')

sleep(3)

print('\n\n[+] All Done. Thank You For Installing Me :D')
